name: Create Ec2 Instance

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "0.12.15"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - name: Verify Terraform version
      run: terraform --version
      
    - name: Set variables
      run: |
        echo "main.tf" > TERRAFORM_FILE
        cat $(cat TERRAFORM_FILE) | grep key=|awk -F '=' '{print $2}'|sed -e 's/"//g' > TAG_KEY
        cat $(cat TERRAFORM_ACTION) | grep "action ="|awk -F '=' '{print $2}'|sed -e 's/"//g' > TAG_ACTION

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -backend-config "bucket=ec2-github" -backend-config "dynamodb_table=ec2-guthub"  -backend-config "region=ap-south-1"     -backend-config "key=$(cat TAG_KEY)"

    - name: Terraform validation
      run: terraform validate

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      if: "create" == "$(cat TAG_ACTION)"
      run: terraform apply -auto-approve -input=false
